### ISSUE TITLE
AttributeError: module 'yaml' has no attribute 'FullLoader'

### ISSUE THREAD

**Issue by woctezuma** [rstrudel/segmenter#11]
On Colab with GPU:

```bash
%cd /content
!git clone https://github.com/rstrudel/segmenter

%cd /content/segmenter
%pip install .

%mkdir -p images
%mkdir -p segmaps
%mkdir -p seg_tiny_mask

%cd /content/segmenter/seg_tiny_mask
!wget https://www.rocq.inria.fr/cluster-willow/rstrudel/segmenter/checkpoints/seg_tiny_mask/checkpoint.pth
!wget https://www.rocq.inria.fr/cluster-willow/rstrudel/segmenter/checkpoints/seg_tiny_mask/variant.yml

%cd /content/segmenter/images
!wget https://i.imgur.com/HpJVhfd.png

%cd /content/segmenter
!python -m segm.inference --model-path seg_tiny_mask/checkpoint.pth -i images/ -o segmaps/ 
```

returns:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/segmenter/segm/inference.py", line 64, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/content/segmenter/segm/inference.py", line 27, in main
    model, variant = load_model(model_path)
  File "/content/segmenter/segm/model/factory.py", line 116, in load_model
    variant = yaml.load(f, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'
```

**Comment by woctezuma** [comment]
Following [this answer on Stackoverflow](https://stackoverflow.com/a/55553392/376454):

```python
import yaml
yaml.__version__
```

returns:
```
'3.13'
```

The issue is solved by running:
```bash
%pip install -U PyYAML
```

So I would suggest to specify the minimal version of PyYAML in the requirements.

**Comment by woctezuma** [comment]
I now get the same error as #10.

```
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3613: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)

/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py:165: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  img = torch.as_tensor(np.asarray(pic))

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/segmenter/segm/inference.py", line 64, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/content/segmenter/segm/inference.py", line 52, in main
    batch_size=2,
  File "/content/segmenter/segm/model/utils.py", line 173, in inference
    seg_maps[i : i + WB] = model.forward(crops[i : i + WB])
  File "/content/segmenter/segm/model/segmenter.py", line 37, in forward
    x = self.encoder(im, return_features=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/segmenter/segm/model/vit.py", line 112, in forward
    x = self.patch_embed(im)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/segmenter/segm/model/vit.py", line 34, in forward
    x = self.proj(im).flatten(2).transpose(1, 2)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 440, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```

**Comment by rstrudel** [comment]
Thanks for opening an issue, I pushed a commit that should fix it. There was a line missing set the model weights on gpu. I tested the inference script on a cpu only and did not catch it. It should be good now.
