### ISSUE TITLE
how can I finetune segmenter in my own dataset?

### ISSUE THREAD

**Issue by nnajeh** [rstrudel/segmenter#20]

**Comment by civdex** [comment]
i can't get results for this task either. 

I have created a custom dataset, called "kvasir" with corresponding file creations with modifications. 

I keep getting an error that produces this error:

After running: 
`python -m segm.train --log-dir seg_tiny_mask --dataset kvasir --backbone vit_tiny_patch16_384 --decoder mask_transformer --batch-size 2 --epochs 2`

`
Traceback (most recent call last):
  File "/home/john/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/john/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/john/Documents/Dev_Linux/segmentation/segmenter/segm/train.py", line 170, in <module>
    main()
  File "/home/john/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/john/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/john/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/john/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/john/Documents/Dev_Linux/segmentation/segmenter/segm/train.py", line 167, in main
    train_loader = create_dataset(dataset_kwargs)
  File "/home/john/Documents/Dev_Linux/segmentation/segmenter/segm/data/factory.py", line 29, in create_dataset
    dataset = KvasirDataset(split=split, **dataset_kwargs)
  File "/home/john/Documents/Dev_Linux/segmentation/segmenter/segm/data/kvasir.py", line 16, in __init__
    super().__init__(
  File "/home/john/Documents/Dev_Linux/segmentation/segmenter/segm/data/base.py", line 43, in __init__
    self.dataset = build_dataset(getattr(self.config.data, f"{self.split}"))
  File "/home/john/anaconda3/lib/python3.8/site-packages/mmseg/datasets/builder.py", line 73, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/john/anaconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: KvasirDataset: __init__() missing 3 required positional arguments: 'image_size', 'crop_size', and 'split'
`

after creating my own custom dataset file called: `Kvasir Dataset`

Which uses the following code from segm/data/kvasir.py

```python
from pathlib import Path

from segm.data.base import BaseMMSeg
from segm.data.utils import dataset_cat_description 
from segm.config import dataset_dir

from mmseg.datasets.builder import DATASETS
from mmseg.datasets.custom import CustomDataset

KVASIR_CONFIG_PATH = Path(__file__).parent / "config" / "kvasir.py"
KVASIR_CATS_PATH = Path(__file__).parent / "config" / "kvasir.yml"

@DATASETS.register_module()
class KvasirDataset(BaseMMSeg):
    def __init__(self, image_size, crop_size, split, **kwargs):
        super().__init__(
            image_size,
            crop_size,
            split,
            KVASIR_CONFIG_PATH,
            **kwargs,
        )
        self.names, self.colors = dataset_cat_description(KVASIR_CATS_PATH)
        self.n_cls = 2
        self.ignore_label = 0
        self.reduce_zero_label = True
    
    def update_default_config(self, config):
        root_dir = dataset_dir()
        path = Path(root_dir) / "kvasir"
        config.data_root = path

        if self.split == "train":
            config.data.train.data_root = path / "KvasirSegChallengeData"
        elif self.split == "trainval":
            config.data.trainval.data_root = path / "KvasirSegChallengeData"
        elif self.split == "val":
            config.data.val.data_root = path / "KvasirSegChallengeData"
        elif self.split == "test":
            config.data.test.data_root = path / "release_test"
        config = super().update_default_config(config)
        return config

    def test_post_process(self, labels):
        return labels + 1
```



Any advice? I can post more of the relevant files, ex: segm/data/config/kvasir.py or segm/data/config/kvasir.yml

**Comment by Shawn94** [comment]
Looking at the error, I think you also need to edit the base Dataset(baseMMSeg), as it requires 3 positional arguments, which you don`t have in your custom dataset.

**Comment by rstrudel** [comment]
We do not plan to support custom dataset training but it should be easier to do once Segmenter is part of mmsegmentation.
