### ISSUE TITLE
KeyError: ''

### ISSUE THREAD

**Issue by SikangSHU** [rstrudel/segmenter#40]
Hello, I run the program in windows. And an error occurred that 
```
D:\Download\anaconda\anaconda\envs\learn\python.exe E:/Learning/Graduate/segmenter/segmenter-master/segm/train.py
Starting process with rank 0...
Process 0 is connected.
All processes are connected.
Traceback (most recent call last):
  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\train.py", line 304, in <module>
    main()
  File "D:\Download\anaconda\anaconda\envs\learn\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\Download\anaconda\anaconda\envs\learn\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\Download\anaconda\anaconda\envs\learn\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Download\anaconda\anaconda\envs\learn\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\train.py", line 76, in main
    model_cfg = cfg["model"][backbone]
KeyError: ''
```
Do you know how to solve it? Thank you!

**Comment by rstrudel** [comment]
Hi @SikangSHU ,
It seems you are not passing any arguments to train.py, try with the command from the readme:
```python
python -m segm.train --log-dir seg_tiny_mask --dataset ade20k \
  --backbone vit_tiny_patch16_384 --decoder mask_transformer
  ```
  Please try to carefully read the readme before opening an issue.

**Comment by SikangSHU** [comment]
> Hi @SikangSHU , It seems you are not passing any arguments to train.py, try with the command from the readme:
> 
> ```python
> python -m segm.train --log-dir seg_tiny_mask --dataset ade20k \
>   --backbone vit_tiny_patch16_384 --decoder mask_transformer
> ```
> 
> Please try to carefully read the readme before opening an issue.

OK. I'm sorry for that. Thank you!

**Comment by rstrudel** [comment]
Alright, I will close this issue then. Good luck with your work!

**Comment by SikangSHU** [comment]
> Alright, I will close this issue then. Good luck with your work!

Hello! I have read it carefully, but it still have an error that
```
(learn) E:\Learning\Graduate\segmenter\segmenter-master>python -m segm.inference --model-path seg_tiny_mask/checkpoint.pth -i images/ -o segmaps/
Traceback (most recent call last):
  File "D:\Download\anaconda\anaconda\envs\learn\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Download\anaconda\anaconda\envs\learn\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\inference.py", line 65, in <module>
    main()
  File "D:\Download\anaconda\anaconda\envs\learn\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\Download\anaconda\anaconda\envs\learn\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\Download\anaconda\anaconda\envs\learn\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Download\anaconda\anaconda\envs\learn\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\inference.py", line 27, in main
    model, variant = load_model(model_path)
  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\model\factory.py", line 119, in load_model
    model = create_segmenter(net_kwargs)
  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\model\factory.py", line 106, in create_segmenter
    encoder = create_vit(model_cfg)
  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\model\factory.py", line 67, in create_vit
    model = VisionTransformer(**model_cfg)
TypeError: __init__() got an unexpected keyword argument 'mlp_ratio'
```

**Comment by SikangSHU** [comment]
![image](https://user-images.githubusercontent.com/95743639/157365861-0f2bdffb-cb8d-4a39-a1ab-7989f6980f36.png)

**Comment by SikangSHU** [comment]
Hello! I have read readme carefully. There is still an error.
```
(learn) E:\Learning\Graduate\segmenter\segmenter-master>python -m segm.eval.miou seg_tiny_mask/checkpoint.pth ade20k --singlescale
Starting process with rank 0...
Process 0 is connected.
All processes are connected.
Traceback (most recent call last):
  File "D:\Download\anaconda\anaconda\envs\learn\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Download\anaconda\anaconda\envs\learn\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\eval\miou.py", line 266, in <module>
    main()
  File "D:\Download\anaconda\anaconda\envs\learn\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\Download\anaconda\anaconda\envs\learn\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\Download\anaconda\anaconda\envs\learn\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Download\anaconda\anaconda\envs\learn\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\eval\miou.py", line 217, in main
    model, variant = load_model(model_path)
  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\model\factory.py", line 119, in load_model
    model = create_segmenter(net_kwargs)
  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\model\factory.py", line 106, in create_segmenter
    encoder = create_vit(model_cfg)
  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\model\factory.py", line 67, in create_vit
    model = VisionTransformer(**model_cfg)
TypeError: __init__() got an unexpected keyword argument 'mlp_ratio'
```

**Comment by SikangSHU** [comment]
Hello. I have read readme and installed all the requirement. But there is still an error that
```
(learn2) E:\Learning\Graduate\segmenter\segmenter-master>python -m segm.eval.miou seg_tiny_mask/checkpoint.pth ade20k --singlescale
Starting process with rank 0...
Process 0 is connected.
All processes are connected.
D:\Download\anaconda\anaconda\envs\learn2\lib\site-packages\torch\nn\functional.py:3613: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
Use normalization: {'mean': (127.5, 127.5, 127.5), 'std': (127.5, 127.5, 127.5)}
2022-03-09 19:06:05,775 - mmseg - INFO - Loaded 2000 images
D:\Download\anaconda\anaconda\envs\learn2\lib\site-packages\torch\utils\data\dataloader.py:481: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 8 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x000001B89AFA2318>
Traceback (most recent call last):
  File "D:\Download\anaconda\anaconda\envs\learn2\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "D:\Download\anaconda\anaconda\envs\learn2\lib\site-packages\torch\utils\data\dataloader.py", line 1328, in __del__
    exitcode = _main(fd)
  File "D:\Download\anaconda\anaconda\envs\learn2\lib\multiprocessing\spawn.py", line 114, in _main
        prepare(preparation_data)
self._shutdown_workers()  File "D:\Download\anaconda\anaconda\envs\learn2\lib\multiprocessing\spawn.py", line 223, in prepare

    _fixup_main_from_name(data['init_main_from_name'])
  File "D:\Download\anaconda\anaconda\envs\learn2\lib\site-packages\torch\utils\data\dataloader.py", line 1295, in _shutdown_workers
  File "D:\Download\anaconda\anaconda\envs\learn2\lib\multiprocessing\spawn.py", line 249, in _fixup_main_from_name
    alter_sys=True)
  File "D:\Download\anaconda\anaconda\envs\learn2\lib\runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
if self._persistent_workers or self._workers_status[worker_id]:  File "D:\Download\anaconda\anaconda\envs\learn2\lib\runpy.py", line 96, in _run_module_code

    mod_name, mod_spec, pkg_name, script_name)
AttributeError  File "D:\Download\anaconda\anaconda\envs\learn2\lib\runpy.py", line 85, in _run_code
:     exec(code, run_globals)
'_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'  File "E:\Learning\Graduate\segmenter\segmenter-master\segm\eval\miou.py", line 9, in <module>

    import torch
  File "D:\Download\anaconda\anaconda\envs\learn2\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 1455] Error loading "D:\Download\anaconda\anaconda\envs\learn2\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
```

**Comment by rstrudel** [comment]
Hi, 
The error seems related to `torch` and its installation rather than this repository.

**Comment by SikangSHU** [comment]
Hi, the version of my torch is 1.9.0 and the file it pointed out exists.
![image](https://user-images.githubusercontent.com/95743639/157668303-93afd17f-ebe6-4045-bdf6-339445a13a5d.png)

**Comment by SikangSHU** [comment]
Is it not necessary to install `torch` that it may cause inconsistency when installing `timm`?

**Comment by rstrudel** [comment]
Hi @SikangSHU ,
The purpose of issues in this repository is not to fix setup related issues. I am not using windows and cannot figure out the details for you. I am trying to help on Segmenter related issues.
